### ISSUE TITLE
What happens if "Slide magnifications 40 do not match expected target magnification"

### ISSUE THREAD

**Issue by ciaobladoo** [digitalpathologybern/hover_next_inference#12]
Thanks for this amazing work. I am trying it on our WSIs. I got this warning "Slide magnifications 40 do not match expected target magnification". (This is interesting since original Hovernet expects 40X rather than 20X). Is there an option to downsample the WSI (i.e., using level 1 instead of level 0 when loading with openslide). Thanks!

**Comment by eliasbaumann** [comment]
Hi @ciaobladoo , thanks for opening this issue! The pipeline is designed to handle any WSI as long as the required resolution is available, but I am guessing something else is wrong in your instance. 

First, the required resolution (in microns per pixel) are defined [here](https://github.com/digitalpathologybern/hover_next_inference/blob/f694ba93e4eca3299381d0a904c08ce3bc88004f/src/constants.py#L51)
Including what the pipeline understands as 20x or 40x magnification.

Do you mind posting the output of this snippet for the WSI you are trying to run? You can e.g. put it into a pastebin or upload a txt. (and remove e.g. the filename).

```
import openslide
sl = openslide.open_slide("/path/to/aaa.mrxs")
print(sl.properties)
```

Also, are you trying to run the pannuke model or lizard model?

**Comment by eliasbaumann** [comment]
Okay so according to this output `'openslide.mpp-x': '0.50290000000000001', 'openslide.mpp-y': '0.50290000000000001',`, your image is scanned at 0.5mpp which is too low res for pannuke. If you want this to run anyways, you can overwrite the required mpp resolution in src/constants, but I would not recommend this, since the pannuke training tiles are from 0.25mpp scans.

**Comment by ciaobladoo** [comment]
I see. In your code the mpp for 20X should be 0.485, correct? Did you observe in your experiments that this kind of discrepancy will make a big difference in terms of segmentation/classification performance? Will I be able to run lizard model on this slide? If not I may need to create a branch and hack into your code so it can take any 20X images regardless of actual mpp.

**Comment by eliasbaumann** [comment]
I havent experimented with this. In the training, zoom and resizing are included as augmentation methods, so I would assume that there is some robustness to different magnifications. Yet the model is only evaluated against the high resolution images. The lizard model should run fine, if not please let me know. 
If you modify this [line](https://github.com/digitalpathologybern/hover_next_inference/blob/f694ba93e4eca3299381d0a904c08ce3bc88004f/src/inference.py#L111) and for example include your own check to run at 20x anyways if there is no 40x mag you would get what you want.

**Comment by ciaobladoo** [comment]
Thank you @eliasbaumann. I will try it out and let you know. Just to clarify, if I run the pannuke model with my WSI, which is 20X, does the code implement resizing the tiles from 20X to 40X?

**Comment by ciaobladoo** [comment]
Hi @eliasbaumann I dig into your code and now understood the inference can run properly for a 20X WSI with pannuke model (the tiles extracted from 20X will be rescaled to 40X). Only that post-process will report NotImplementedError. I may try to implement this myself. Could you let me know what is the main challenge that is preventing this to be implemented (is it in processing the prediction map to get the nuclei, or stitching tile results to a WSI)? Thanks!

**Comment by eliasbaumann** [comment]
Hi @ciaobladoo , sorry for not getting back to you about this sooner: If I remember correctly, I simply put this NotImplementedError there because I never tried and verified whether it works. I just ran a sample which only has 0.5mpp as highest resolution and uncommented [lines 650-653](https://github.com/digitalpathologybern/hover_next_inference/blob/f694ba93e4eca3299381d0a904c08ce3bc88004f/src/post_process_utils.py#L650C1-L653C18) and the output seems fine? If you try this and experience any issues in the output, please let me know.

**Comment by ciaobladoo** [comment]
Sorry I forgot to reply. Yes your suggestion worked. The results on our dataset is pretty good. Except that the models trained on Lizard dataset was missing some nuclei in our dataset compared to the models that trained on pannuke. But overall it is very good.

**Comment by eliasbaumann** [comment]
No worries, thanks for getting back to me. For the Lizard model, you could manually adjust the object size thresholds to make sure more small objects are included. The thresholds are optimized for the Lizard dataset, which may not always be the best choice in practice
