### ISSUE TITLE
Masked inference

### ISSUE THREAD

**Issue by sandman002** [digitalpathologybern/hover_next_inference#13]
Is there a way to input low resolution mask so that the inference runs on the foreground tiles only?

**Comment by eliasbaumann** [comment]
Hey @sandman002 , thanks for opening this issue! Currently there is a very basic foreground background estimation built into the WSI inference pipeline. If your WSI is has a non-white / dark background, this will fail, as its simple tresholding. Check the [following lines for further details.](https://github.com/digitalpathologybern/hover_next_inference/blob/f694ba93e4eca3299381d0a904c08ce3bc88004f/src/data_utils.py#L428)

This process will not happen if this condition does not hold: [(Link to line)](https://github.com/digitalpathologybern/hover_next_inference/blob/f694ba93e4eca3299381d0a904c08ce3bc88004f/src/data_utils.py#L202)
`
if remove_background and "thumbnail" in self.s.associated_images:
`
If your input does not have a thumbnail, you may have to edit this code to extract e.g. the lowest possible resolution image from a WSI pyramid and use that as mask instead, or you directly supply a mask, by adding a mask argument to the WholeSlideDataset `__init__`.

For example like this:

```
class WholeSlideDataset(Dataset):
    def __init__(
        self,
        path: str,
        crop_sizes_px: Optional[List[int]] = None,
        crop_magnifications: Optional[List[float]] = None,
        transform: Optional[Callable] = None,
        padding_factor: Optional[float] = 0.5,
        remove_background: Optional[bool] = True,
        remove_oob: Optional[bool] = True,
        remove_alpha: Optional[bool] = True,
        ratio_object_thresh: Optional[float] = 1e-3,
        custom_mask = None,
    ) -> None:
...

if remove_background:
    # Extract image thumbnail from slide metadata
    if self.custom_mask is not None:
      img_thumb = self.custom_mask 
    else:
      img_thumb = # Load lowest mag openslide WSI level
```

I hope this answers your question and gives you a starting point on how to do it. If you have further questions, feel free to ask!

**Comment by eliasbaumann** [comment]
Hey, as I haven't heard from you in a while, i am closing this issue assuming that you either managed or moved on. Feel free to re-open if thats not the case.
