### ISSUE TITLE
Towards an efficient polygon output

### ISSUE THREAD

**Issue by eliasbaumann** [digitalpathologybern/hover_next_inference#6]
Currently the polygon output function re-reads the instance map, searches for all nuclei and then creates polygons from them. This is unnecessarily slow and could be improved by properly integrating this output modality into the workflow.

(related: #4 )

**Comment by eliasbaumann** [comment]
Update f97e1fd
Changed the geojson output functions to be a little bit faster and more efficient via opencv and reducing the precision

**Comment by ciaobladoo** [comment]
How do I output geojson? It's not clear from the README. Thanks!

**Comment by eliasbaumann** [comment]
Hey @ciaobladoo , you need to add `--save_polygon` when running main.py. I've added this in the readme now, thanks for pointing it out!
